#
# Copyright (C) 2020 Geon Technologies, LLC
#
# This file is part of FINS.
#
# FINS is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# FINS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

variables:
stages:
    - prereqs
    - test-core
    - test-backends
image: centos:7

.install-prereqs: &install-prereqs |
    yum install -y epel-release
    yum install -y python36 python36-pip python-jinja2 octave make gcc glibc.i686
    python3 -m pip install --upgrade pip setuptools
    python3 -m pip install .

test-core:
    stage: test-core
    before_script:
        - *install-prereqs
    script:
        - 'cd test/node'
        - 'fins fins.json'
        - 'cd ../application'
        - 'fins application_test.json'
        - 'cd ../../tutorials/power_converter'
        - 'fins fins.json'
        - 'cd ../power_application'
        - 'fins fins.json'
    tags:
        - fpga

test-vivado:
    stage: test-backends
    variables:
        VIVADO_VERSION: '2019.1'
        VIVADO_PATH: '/opt/fpga/Xilinx/Vivado/$VIVADO_VERSION'
    except:
        variables:
            [ $VIVADO_DISABLE == 'true' ]
    before_script:
        - *install-prereqs
        - 'python3 -m pip install ./vivado'
    script:
        - 'source $VIVADO_PATH/settings64.sh'
        - 'cd test/'
        - './test_backend.sh vivado'
    tags:
        - fpga

test-quartus:
    stage: test-backends
    variables:
        QUARTUS_VERSION: '19.4'
        QUARTUS_PATH: '/opt/fpga/Intel/intelFPGA_pro/$QUARTUS_VERSION'
    except:
        variables:
            [ $QUARTUS_DISABLE == 'true' ]
    before_script:
        - *install-prereqs
        - 'python3 -m pip install ./quartus'
    script:
        - 'export PATH=$PATH:$QUARTUS_PATH/quartus/bin:$QUARTUS_PATH/modelsim_ase/bin:$QUARTUS_PATH/qsys/bin'
        - 'cd test/'
        - './test_backend.sh quartus'
    tags:
        - fpga
