#
# Copyright (C) 2024 Geon Technologies, LLC
#
# This file is part of FINS.
#
# FINS is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# FINS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

stages:
    - prereqs
    - test-core
    - test-backends
    - package
image: ubuntu:20.04

.install-prereqs: &install-prereqs |
    echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    apt-get update
    apt-get install -y python3-pip octave python-is-python3 locales libtinfo5 libncurses5
    python3 -m pip install --upgrade pip setuptools
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
    export LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
    python3 -m pip install .

test-core:
    stage: test-core
    before_script:
        - *install-prereqs
    script:
        - 'cd test/'
        - './test_core.sh'
    tags:
        - fpga

test-vivado 2021.2:
    stage: test-backends
    variables:
        VIVADO_VERSION: '2021.2'
        VIVADO_PATH: '/opt/fpga/Xilinx/Vivado/$VIVADO_VERSION'
    before_script:
        - *install-prereqs
        - 'python3 -m pip install ./vivado'
    script:
        - 'source $VIVADO_PATH/settings64.sh'
        # See https://support.xilinx.com/s/question/0D52E000079NURRSA4/synthesis-failed-abnormal-termination-tcmalloc-large-allocation?language=en_US
        - export LD_PRELOAD=/lib/x86_64-linux-gnu/libudev.so.1
        - 'cd test/'
        - './test_backend.sh vivado'
    artifacts:
        when: on_failure
        paths:
            - test/**/log/*
            - tutorial/**/log/*
    except:
        variables:
            [ $VIVADO_DISABLE == 'true' ]
    tags:
        - fpga

test-vivado 2022.2:
    stage: test-backends
    variables:
        VIVADO_VERSION: '2022.2'
        VIVADO_PATH: '/opt/fpga/Xilinx/Vivado/$VIVADO_VERSION'
    before_script:
        - *install-prereqs
        - 'python3 -m pip install ./vivado'
    script:
        - 'source $VIVADO_PATH/settings64.sh'
        # See https://support.xilinx.com/s/question/0D52E000079NURRSA4/synthesis-failed-abnormal-termination-tcmalloc-large-allocation?language=en_US
        - export LD_PRELOAD=/lib/x86_64-linux-gnu/libudev.so.1
        - 'cd test/'
        - './test_backend.sh vivado'
    artifacts:
        when: on_failure
        paths:
            - test/**/log/*
            - tutorial/**/log/*
    except:
        variables:
            [ $VIVADO_DISABLE == 'true' ]
    tags:
        - fpga

# test-quartus:
#     stage: test-backends
#     variables:
#         QUARTUS_VERSION: '19.4'
#         QUARTUS_PATH: '/opt/fpga/Intel/intelFPGA_pro/$QUARTUS_VERSION'
#     before_script:
#         - *install-prereqs
#         - 'python3 -m pip install ./quartus'
#     script:
#         - 'export PATH=$PATH:$QUARTUS_PATH/quartus/bin:$QUARTUS_PATH/modelsim_ase/bin:$QUARTUS_PATH/qsys/bin'
#         - 'cd test/'
#         - './test_backend.sh quartus'
#     artifacts:
#         when: on_failure
#         paths:
#             - test/**/log/*
#             - tutorial/**/log/*
#     except:
#         variables:
#             [ $QUARTUS_DISABLE == 'true' ]
#     tags:
#         - fpga