include:
    - local: '.gitlab-ci.yml'
    - project: common/common
      file: 'common-ci.yml'

variables:
    VIVADO_DISABLE: "true"

rpmbuild:rrpucs:
    extends: .rpmbuild
    rules:
        - if: '$CI_COMMIT_BRANCH == "rrpucs"'
        - when: manual
          allow_failure: true
